# Generated by Django 3.2.8 on 2021-11-07 09:40

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(help_text='The image should be 450x300 && put "coppy image address" here.', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Middle_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', froala_editor.fields.FroalaField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('small_disc', froala_editor.fields.FroalaField()),
                ('image_URL', models.ImageField(help_text='the image should be 600x300', upload_to='subjects')),
                ('disc', froala_editor.fields.FroalaField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
