# Generated by Django 3.2.8 on 2021-11-09 05:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A_Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(help_text='Make sure the img is: 600x600', upload_to='images/')),
                ('name', models.CharField(max_length=20)),
                ('changing_text', models.TextField(help_text='Type like this: Designer, Developer, Freelancer', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='A_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='type like this: bx bxl-twitter', max_length=20)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='B_About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', ckeditor.fields.RichTextField()),
                ('img', models.ImageField(upload_to='B_About/')),
                ('text_bold', models.TextField(max_length=100)),
                ('text_small', ckeditor.fields.RichTextField()),
                ('birthday', models.DateField()),
                ('website', models.URLField()),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('degree', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('freelancer', models.BooleanField()),
                ('botom_text', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='C_Skil_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='D_Skil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('val', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='E_resume_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_resume', ckeditor.fields.RichTextField(blank=True)),
                ('text_summary', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='F_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='G_Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bold_text1', models.CharField(max_length=100)),
                ('session1', models.CharField(max_length=10)),
                ('text1', ckeditor.fields.RichTextField(blank=True)),
                ('text2', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='H_Services_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='I_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Put bootstrap icon like this: bi bi-briefcase-fill', max_length=50)),
                ('sub', ckeditor.fields.RichTextField(blank=True)),
                ('text', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='J_Portfolio_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='K_Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('app', 'App'), ('card', 'Game'), ('web', 'Web')], max_length=5)),
                ('image', models.ImageField(help_text='Make sure the img is: 800x600', upload_to='K_Portfolio/')),
                ('urlname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='L_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('location', models.TextField(help_text='Give only the link here like: https://www.google.com/maps/embed?', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='M_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('sub', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
